# Documentation:
# http://flutter.dev/go/i18n-user-guide
arb-dir: lib/src/l10n
template-arb-file: campguru_en.arb
synthetic-package: false
output-class: CampguruLocalizations
output-localization-file: localizations.dart
preferred-supported-locales: "en"
use-deferred-loading: false
untranslated-messages-file: lib/src/l10n/missing_localizations.json
nullable-getter: false