name: executable
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.16+16

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  presentation:
    path: ../presentation


  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  injectable: ^2.3.2
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  package_rename_plus: ^1.0.1

flutter:
  uses-material-design: true