name: presentation
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../domain
  components:
    path: ../components

  auto_route: ^7.1.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  skeletonizer: ^1.1.0
  intl: ^0.18.1
  flutter_form_builder: ^9.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.3.1
  flutter_map_tile_caching: ^9.0.1
  grouped_list: ^5.1.2
  dart_date: ^1.3.3
  localizations:
    path: ../localizations
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.0.0

flutter:
  uses-material-design: true

